### ISSUE TITLE
How to conduct dense and sparse sampling ?

### ISSUE THREAD

**Issue by Fly2flies** [doc-doc/HQGA#1]
Hi, thanks you for sharing such a great work.
I would like to know how to make dense sampling and sparse sampling after uniformly sampling K clip frames.

After sampling K clip frames _c1,...,cK_

- take these K frame as the middle frame and sample 16 consecutive frames forward and backward to calculate the motion features ?
- Or uniformly 32 frames from all frames from c(i-1) to c(i+1) to calculate the motion features ? 

Which of the above methods is corresponding to the paper ?

**Comment by doc-doc** [comment]
Thanks for your interest.  We adopt the 1st method and sample 16 frames (8 forward / backward) centered at the key frame.

**Comment by Fly2flies** [comment]
> Thanks for your interest. We adopt the 1st method and sample 16 frames (8 forward / backward) centered at the key frame.
Thank you for your reply. I would also like to know how much memory is needed to store all the TGIF-QA data and how to compress and store the extracted features ?

**Comment by Fly2flies** [comment]
> Thanks for your interest. We adopt the 1st method and sample 16 frames (8 forward / backward) centered at the key frame.

Thank you for your reply. I would also like to know how much memory is needed to store all the TGIF-QA data and how to compress and store the extracted features ?

**Comment by doc-doc** [comment]
The raw TGIF_full dataset need about 124G. The features are store in .h5 files and need about 40G for each sub-task.
